### ISSUE TITLE
folder "default_template"

### ISSUE THREAD

**Issue by scottcwilson** [torvista/Zen-Cart_CEON-URI-Mapping#16]
There's a folder `includes/templates/default_template/`.

Is this supposed to be includes/templates/template_default/` or `includes/templates/YOUR_TEMPLATE/` ?

**Comment by torvista** [comment]
This folder was originally named STORE_TEMPLATE and the files are based on the template_default files. Maybe I made a mistake or deliberately named it as such to prevent overwriting anything...a mistake is always a safe bet these days.

I think this should go back to being STORE_TEMPLATE to match the documentation.

**Comment by torvista** [comment]
Done: https://github.com/torvista/Zen-Cart_CEON-URI-Mapping/commit/af74a794e8417beae533a34941488a3a622435ec
