### ISSUE TITLE
Review use of \includes\init_includes\overrides\init_add_crumbs.php

### ISSUE THREAD

**Issue by torvista** [torvista/Zen-Cart_CEON-URI-Mapping#22]
Compare to ZC210 for use of observer.

**Comment by torvista** [comment]
File not required from ZC158+.
Removed: https://github.com/torvista/Zen-Cart_CEON-URI-Mapping/commit/6393098195d78425c1becefdf9a6c69865e0a8d3

**Comment by mc12345678** [comment]
Still required in v1.5.8 and v1.5.8a, but not in those beyond. Currently known "next" version was 2.0.0; however, version 2.1.0 is the current production use version.

**Comment by torvista** [comment]
Thanks for the clarification.
