### ISSUE TITLE
Code review for 156

### ISSUE THREAD

**Issue by mesnitu** [torvista/zen-cart_CEON-URI-Mapping#6]
Hi @torvista, @mc12345678, @Zen4All 
I've made a update for 156. I think 99% is ready, and maybe the ceon team can take advantage (or not) from this update. 
Mostly was diffs, some files were added, others removed since they no longer in use.
Some CEON blocks were just placed according to the zc156 way of dealing with products. 

The core code itself : 

$num_uri_mappings = sizeof($this->_uri_mappings); ( was getting a php warning) 

'automatic_version_checking' => (int)$this->_automatic_version_checking ( for mysql57) 

Some places the $contents[] is not used ( others still is) , so it was a matter of checking zc version and display according. 

... and as I recall, that's was it. 
There are a couple of issues related to php warnings, that I have in "issues"

If you want to check and test : https://github.com/mesnitu/zen-cart_CEON-URI-Mapping

oh ... also the checks on files and configuration: I've removed (comment) the files that are no longer needed, but, now, other checks have to be made. But that's not a priority.

best regards

**Comment by torvista** [comment]
Well done...I cannot look at this in the near future, so hopefully others will step in....

**Comment by mesnitu** [comment]
Hi
I was later contacted by the ceon team. The update is popping up, and uses a completely different structure for zc156, so actually, all this stuff actually null. Don't bother to look up.

**Comment by torvista** [comment]
How annoying, for your time spent. Thanks for making the effort anyway.
